name: mecab_for_flutter
description: Flutter plugin which provides binding to Mecab library (Japanese Morphological Analyzer)
version: 2.0.0
homepage:
  https://github.com/captaindario/mecab_for_flutter
funding:
  - https://github.com/sponsors/CaptainDario
  - https://buymeacoffee.com/dariyooo
  - https://www.patreon.com/DaAppLab

environment:
  sdk: '>=2.16.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  mecab_for_dart: #^2.0.0
    path: /Users/darioklepoch/dev/flutter_packages/mecab_for_dart/

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

